
version: '1'

services:
  db:
    image: postgres:14.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    container_name: muni_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
   